name: CI

on:
  push:
    branches: main
    tags:
      - 'v*.*.*'
  pull_request:
    types: [opened, synchronize, reopened]
    branches: main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: docker-compose -f test/docker-compose.yml run test
